### PR TITLE
New Feature that supports environment variables

### PR DESCRIPTION
**Pull request by jonathannewell**
Hello,

This pull request is a new feature to allow for the binding of environment variables to an app during a deploy. I tried to follow the general pattern for how you have implemented things and not add any new dependencies. I updated and added new tests for the work I have done. Hopefully, I have met any coverage goals you have for the project. 

Please advise if I need to change/add anything. 

I am also interested in adding a capability that allows Deployadactyl to run as a command line utility. Is that something that would be acceptable to you all?

Oh, and sorry about the two commits. I had already pushed when I realized I forgot to update the tests! Actually,  I have probably not done the git part of this correct (according to your guidelines). I am not a git super guru so if I need to change something please advise.

Thanks,

Jon Newell

### CODE REVIEW

**Comment by trayo** [comment]
@jonathannewell Hey Jonathan! Thanks for your contribution!

I'm going to review this later today with some comments.

**Comment by jonathannewell** [comment]
@trayo Just checking in. Doesn't look like git got updated from circleci with status of PR build. Also, have you had a chance to begin reviewing? Cheers, Jon

**Comment by trayo** [comment]
@jonathannewell I had the chance to look over it, but didn't send the review yet. If you don't mind I'd like to see the fixes for the `debugf` and `infof` in a separate PR.

Also, what is the use case for the environment variable functionality? It seems like it would allow a user to pass environment variables from the CURL request body to Deployadactyl and then write those environment variables to the manifest? I think this is what I'm seeing, but I'd like to confirm.

If that's the case the Cloud Foundry manifest already allows you to specify the environment variables so it seems a little redundant.

**Comment by jonathannewell** [comment]
@trayo I can put the logging fixes into a separate PR. Not problem. 

As far as the use case for environment variables.

Yes, this allows for the specification of environment variables at deploy time. Think of it as late-binding environment variables to the app at deploy time. The problem with hard coding them into the manifest is that you then end up storing them in source control (assuming your manifest is source controlled). Which could expose things you don't want in your source control system. For example, lets say you have certain environment variables/config that specifies the identity your app needs to do things like interact with a configuration service for bootstrap configuration. You want to specify that using an environment variable but you don't want to expose that identity in source control.  In our case our build pipeline knows the service's name it is deploying and performs a lookup into "vault" to retrieve the identity information and today it basically does as follows:

     cf push {app-name} --no-start
     cf set-env {app-name} {name} {value} (for each var) 
     --> _This has to be done after the push because if it's the first deploy cf won't know about the app..._
     cf start {app-name} 

We were hoping to leverage Deploydactyl and get the awesomeness of the multi-foundation blue/green deploy capability but require a way for our services to get env. variables set dynamically. I opted to update the manifest dynamically rather than use the cf set-env command dynamically because I felt it was a little cleaner and less impactful on the deploydactyl code-base.  Is this making more sense now? Or am I smoking my socks?  :)

How do you want me to go about separating the loggin fixes. Do you want me to close this pull request. Create a new one with just the logging and then create another new one with the feature without the logging? Please advise.

**Comment by trayo** [comment]
Ah, yes I definitely understand. We had that issue as well, but have a Jenkins plugin that handles doing the environment variable substitution into the manifest.

The manifest will look like:
```
applications:
- name: hi
   env:
   - first_env:  ${ENV_VAR}
```

We used to have some code that would set environment variables from the request and were doing roughly the same thing.

I would like to see some additional tests in `deployer_test.go` in order to have full coverage on the new code that was added to `deployer.go`

Regarding the CircleCI issue: It won't run again unless you push another commit or I rerun it.

Regarding the logging problems: If you're familiar enough with git, those changes could be uncommited and then the rest of the code force pushed to the same branch. Actually, it might be easier for you to make a new PR with the changes because I was also going to ask to have you send the PR against our `develop` branch.

Let me know if you need some help, we might be able to do a video call to resolve any issues. I'm also going to send a PR review with minor changes that should be easy fixes.

**Comment by trayo** [comment]
@jonathannewell The team and I were talking more about the feature you want to implement and it makes sense to use to write an event handler to pull the environment variables from the request and put them into the manifest.

This way it would be independently testable and not interfere with users who may choose to not use the feature.

We would be happy to make it, but you are more than welcome to try it out and we would be happy to look over it to ensure it would work.

**Comment by jonathannewell** [comment]
@trayo ok, I am happy to implement but I do have a question/concern. Being that event handlers are asynchronous how are you all thinking of ensuring the event is processed and the manifest is updated before the deploy begins? Are you thinking of some sort of a wait loop that looks for corresponding handler processing complete events before starting the deploy? Or am I missing some capability built in to GO?  
I like the idea, I am just concerned with the "environment variable plugin" being invoked asynchronously....

**Comment by trayo** [comment]
@jonathannewell Our event handling isn't done asynchronously. It will wait for all event handlers to finish before continuing with a deployment. If it's required to stop a deployment if the manifest is not correct, make sure to throw an error back to Deployadactyl

**Comment by jonathannewell** [comment]
@trayo  Ok. I will close this request and submit a new one following this approach. Thanks!

**Comment by jonathannewell** [comment]
Closing per discussion.

**Pull request closed without merging**
